# Generated by Django 3.1.7 on 2021-02-27 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='homeword',
        ),
        migrations.AddField(
            model_name='upload',
            name='homework',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='panel.homework'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
